/**
 * Communities (towns / city districts) grouped by the backend region keys from
 * GET /api/config. `value` is the canonical Latin form stored in the order's
 * `delivery.city` field, matching the values already used in the database.
 */
export interface Community {
  value: string;
  hy: string;
  en: string;
  ru: string;
}

export const COMMUNITIES: Record<string, Community[]> = {
  yerevan: [
    { value: 'Yerevan', hy: 'Երևան', en: 'Yerevan', ru: 'Ереван' },
    { value: 'Ajapnyak', hy: 'Աջափնյակ', en: 'Ajapnyak', ru: 'Аджапняк' },
    { value: 'Arabkir', hy: 'Արաբկիր', en: 'Arabkir', ru: 'Арабкир' },
    { value: 'Avan', hy: 'Ավան', en: 'Avan', ru: 'Аван' },
    { value: 'Davtashen', hy: 'Դավթաշեն', en: 'Davtashen', ru: 'Давташен' },
    { value: 'Erebuni', hy: 'Էրեբունի', en: 'Erebuni', ru: 'Эребуни' },
    { value: 'Kanaker-Zeytun', hy: 'Քանաքեռ-Զեյթուն', en: 'Kanaker-Zeytun', ru: 'Канакер-Зейтун' },
    { value: 'Kentron', hy: 'Կենտրոն', en: 'Kentron', ru: 'Кентрон' },
    { value: 'Malatia-Sebastia', hy: 'Մալաթիա-Սեբաստիա', en: 'Malatia-Sebastia', ru: 'Малатия-Себастия' },
    { value: 'Nor Nork', hy: 'Նոր Նորք', en: 'Nor Nork', ru: 'Нор Норк' },
    { value: 'Nork-Marash', hy: 'Նորք-Մարաշ', en: 'Nork-Marash', ru: 'Норк-Мараш' },
    { value: 'Nubarashen', hy: 'Նուբարաշեն', en: 'Nubarashen', ru: 'Нубарашен' },
    { value: 'Shengavit', hy: 'Շենգավիթ', en: 'Shengavit', ru: 'Шенгавит' },
  ],
  aragatsotn: [
    { value: 'Ashtarak', hy: 'Աշտարակ', en: 'Ashtarak', ru: 'Аштарак' },
    { value: 'Aparan', hy: 'Ապարան', en: 'Aparan', ru: 'Апаран' },
    { value: 'Talin', hy: 'Թալին', en: 'Talin', ru: 'Талин' },
    { value: 'Byurakan', hy: 'Բյուրական', en: 'Byurakan', ru: 'Бюракан' },
    { value: 'Oshakan', hy: 'Օշական', en: 'Oshakan', ru: 'Ошакан' },
    { value: 'Alagyaz', hy: 'Ալագյազ', en: 'Alagyaz', ru: 'Алагяз' },
    { value: 'Kosh', hy: 'Կոշ', en: 'Kosh', ru: 'Кош' },
    { value: 'Voskevaz', hy: 'Ոսկեվազ', en: 'Voskevaz', ru: 'Воскеваз' },
    { value: 'Tsaghkahovit', hy: 'Ծաղկահովիտ', en: 'Tsaghkahovit', ru: 'Цахкаховит' },
    { value: 'Ujan', hy: 'Ուջան', en: 'Ujan', ru: 'Уджан' },
  ],
  ararat: [
    { value: 'Artashat', hy: 'Արտաշատ', en: 'Artashat', ru: 'Арташат' },
    { value: 'Ararat', hy: 'Արարատ', en: 'Ararat', ru: 'Арарат' },
    { value: 'Vedi', hy: 'Վեդի', en: 'Vedi', ru: 'Веди' },
    { value: 'Masis', hy: 'Մասիս', en: 'Masis', ru: 'Масис' },
    { value: 'Vostan', hy: 'Ոստան', en: 'Vostan', ru: 'Востан' },
    { value: 'Dvin', hy: 'Դվին', en: 'Dvin', ru: 'Двин' },
    { value: 'Burastan', hy: 'Բուրաստան', en: 'Burastan', ru: 'Бурастан' },
    { value: 'Hayanist', hy: 'Հայանիստ', en: 'Hayanist', ru: 'Аянист' },
    { value: 'Sis', hy: 'Սիս', en: 'Sis', ru: 'Сис' },
    { value: 'Sayat-Nova', hy: 'Սայաթ-Նովա', en: 'Sayat-Nova', ru: 'Саят-Нова' },
  ],
  armavir: [
    { value: 'Armavir', hy: 'Արմավիր', en: 'Armavir', ru: 'Армавир' },
    { value: 'Vagharshapat', hy: 'Վաղարշապատ', en: 'Vagharshapat', ru: 'Вагаршапат' },
    { value: 'Metsamor', hy: 'Մեծամոր', en: 'Metsamor', ru: 'Мецамор' },
    { value: 'Sardarapat', hy: 'Սարդարապատ', en: 'Sardarapat', ru: 'Сардарапат' },
    { value: 'Baghramyan', hy: 'Բաղրամյան', en: 'Baghramyan', ru: 'Баграмян' },
    { value: 'Mrgashat', hy: 'Մրգաշատ', en: 'Mrgashat', ru: 'Мргашат' },
    { value: 'Nalbandyan', hy: 'Նալբանդյան', en: 'Nalbandyan', ru: 'Налбандян' },
    { value: 'Norakert', hy: 'Նորակերտ', en: 'Norakert', ru: 'Норакерт' },
    { value: 'Arevik', hy: 'Արևիկ', en: 'Arevik', ru: 'Аревик' },
    { value: 'Taronik', hy: 'Տարոնիկ', en: 'Taronik', ru: 'Тароник' },
  ],
  gegharkunik: [
    { value: 'Gavar', hy: 'Գավառ', en: 'Gavar', ru: 'Гавар' },
    { value: 'Sevan', hy: 'Սևան', en: 'Sevan', ru: 'Севан' },
    { value: 'Martuni', hy: 'Մարտունի', en: 'Martuni', ru: 'Мартуни' },
    { value: 'Vardenis', hy: 'Վարդենիս', en: 'Vardenis', ru: 'Варденис' },
    { value: 'Chambarak', hy: 'Ճամբարակ', en: 'Chambarak', ru: 'Чамбарак' },
    { value: 'Vardenik', hy: 'Վարդենիկ', en: 'Vardenik', ru: 'Варденик' },
    { value: 'Karchaghbyur', hy: 'Կարճաղբյուր', en: 'Karchaghbyur', ru: 'Карчагбюр' },
    { value: 'Tsovazard', hy: 'Ծովազարդ', en: 'Tsovazard', ru: 'Цовазард' },
    { value: 'Lchashen', hy: 'Լճաշեն', en: 'Lchashen', ru: 'Лчашен' },
    { value: 'Sarukhan', hy: 'Սարուխան', en: 'Sarukhan', ru: 'Сарухан' },
  ],
  lori: [
    { value: 'Vanadzor', hy: 'Վանաձոր', en: 'Vanadzor', ru: 'Ванадзор' },
    { value: 'Alaverdi', hy: 'Ալավերդի', en: 'Alaverdi', ru: 'Алаверди' },
    { value: 'Stepanavan', hy: 'Ստեփանավան', en: 'Stepanavan', ru: 'Степанаван' },
    { value: 'Spitak', hy: 'Սպիտակ', en: 'Spitak', ru: 'Спитак' },
    { value: 'Tashir', hy: 'Տաշիր', en: 'Tashir', ru: 'Ташир' },
    { value: 'Tumanyan', hy: 'Թումանյան', en: 'Tumanyan', ru: 'Туманян' },
    { value: 'Akhtala', hy: 'Ախթալա', en: 'Akhtala', ru: 'Ахтала' },
    { value: 'Odzun', hy: 'Օձուն', en: 'Odzun', ru: 'Одзун' },
    { value: 'Metsavan', hy: 'Մեծավան', en: 'Metsavan', ru: 'Мецаван' },
  ],
  kotayk: [
    { value: 'Abovyan', hy: 'Աբովյան', en: 'Abovyan', ru: 'Абовян' },
    { value: 'Hrazdan', hy: 'Հրազդան', en: 'Hrazdan', ru: 'Раздан' },
    { value: 'Charentsavan', hy: 'Չարենցավան', en: 'Charentsavan', ru: 'Чаренцаван' },
    { value: 'Byureghavan', hy: 'Բյուրեղավան', en: 'Byureghavan', ru: 'Бюрегаван' },
    { value: 'Nor Hachn', hy: 'Նոր Հաճն', en: 'Nor Hachn', ru: 'Нор Ачн' },
    { value: 'Yeghvard', hy: 'Եղվարդ', en: 'Yeghvard', ru: 'Егвард' },
    { value: 'Tsaghkadzor', hy: 'Ծաղկաձոր', en: 'Tsaghkadzor', ru: 'Цахкадзор' },
    { value: 'Arzni', hy: 'Արզնի', en: 'Arzni', ru: 'Арзни' },
    { value: 'Balahovit', hy: 'Բալահովիտ', en: 'Balahovit', ru: 'Балаовит' },
    { value: 'Mayakovski', hy: 'Մայակովսկի', en: 'Mayakovski', ru: 'Маяковский' },
  ],
  shirak: [
    { value: 'Gyumri', hy: 'Գյումրի', en: 'Gyumri', ru: 'Гюмри' },
    { value: 'Artik', hy: 'Արթիկ', en: 'Artik', ru: 'Артик' },
    { value: 'Maralik', hy: 'Մարալիկ', en: 'Maralik', ru: 'Маралик' },
    { value: 'Amasia', hy: 'Ամասիա', en: 'Amasia', ru: 'Амасия' },
    { value: 'Ashotsk', hy: 'Աշոցք', en: 'Ashotsk', ru: 'Ашоцк' },
    { value: 'Panik', hy: 'Փանիկ', en: 'Panik', ru: 'Паник' },
    { value: 'Mets Mantash', hy: 'Մեծ Մանթաշ', en: 'Mets Mantash', ru: 'Мец Манташ' },
    { value: 'Azatan', hy: 'Ազատան', en: 'Azatan', ru: 'Азатан' },
    { value: 'Mayisyan', hy: 'Մայիսյան', en: 'Mayisyan', ru: 'Майисян' },
  ],
  syunik: [
    { value: 'Kapan', hy: 'Կապան', en: 'Kapan', ru: 'Капан' },
    { value: 'Goris', hy: 'Գորիս', en: 'Goris', ru: 'Горис' },
    { value: 'Sisian', hy: 'Սիսիան', en: 'Sisian', ru: 'Сисиан' },
    { value: 'Meghri', hy: 'Մեղրի', en: 'Meghri', ru: 'Мегри' },
    { value: 'Agarak', hy: 'Ագարակ', en: 'Agarak', ru: 'Агарак' },
    { value: 'Tatev', hy: 'Տաթև', en: 'Tatev', ru: 'Татев' },
    { value: 'Shinuhayr', hy: 'Շինուհայր', en: 'Shinuhayr', ru: 'Шинуайр' },
    { value: 'Khndzoresk', hy: 'Խնձորեսկ', en: 'Khndzoresk', ru: 'Хндзореск' },
  ],
  vayots_dzor: [
    { value: 'Yeghegnadzor', hy: 'Եղեգնաձոր', en: 'Yeghegnadzor', ru: 'Ехегнадзор' },
    { value: 'Jermuk', hy: 'Ջերմուկ', en: 'Jermuk', ru: 'Джермук' },
    { value: 'Vayk', hy: 'Վայք', en: 'Vayk', ru: 'Вайк' },
    { value: 'Areni', hy: 'Արենի', en: 'Areni', ru: 'Арени' },
    { value: 'Yeghegis', hy: 'Եղեգիս', en: 'Yeghegis', ru: 'Ехегис' },
    { value: 'Malishka', hy: 'Մալիշկա', en: 'Malishka', ru: 'Малишка' },
    { value: 'Gladzor', hy: 'Գլաձոր', en: 'Gladzor', ru: 'Гладзор' },
    { value: 'Shatin', hy: 'Շատին', en: 'Shatin', ru: 'Шатин' },
    { value: 'Hermon', hy: 'Հերմոն', en: 'Hermon', ru: 'Гермон' },
  ],
  tavush: [
    { value: 'Ijevan', hy: 'Իջևան', en: 'Ijevan', ru: 'Иджеван' },
    { value: 'Dilijan', hy: 'Դիլիջան', en: 'Dilijan', ru: 'Дилижан' },
    { value: 'Noyemberyan', hy: 'Նոյեմբերյան', en: 'Noyemberyan', ru: 'Ноемберян' },
    { value: 'Berd', hy: 'Բերդ', en: 'Berd', ru: 'Берд' },
    { value: 'Ayrum', hy: 'Այրում', en: 'Ayrum', ru: 'Айрум' },
    { value: 'Achajur', hy: 'Աչաջուր', en: 'Achajur', ru: 'Ачаджур' },
    { value: 'Haghartsin', hy: 'Հաղարծին', en: 'Haghartsin', ru: 'Агарцин' },
    { value: 'Azatamut', hy: 'Ազատամուտ', en: 'Azatamut', ru: 'Азатамут' },
  ],
};

export const communitiesFor = (region: string): Community[] => COMMUNITIES[region] ?? [];
